version: "3"
services: 
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - "6379"

  db: 
    env_file: 
      - .env
    image: postgres

  web:
    env_file: 
      - .env
    image: femibabs/e-commerce
    container_name: e-commerce
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - /usr/src/app
    links:
        - redis
    command: ["bash", "-c","while !</dev/tcp/db/5432; do sleep 1; done; npm run devstart"]
    environment:
      - ECOMMERCE_NODE_ENV=development
      - REDIS_URL=redis://cache
      - ECOMMERCE_DATABASE_DEV_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5431/${POSTGRES_DB}
    depends_on: 
      - redis
      - db