# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
  
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: e_commerce_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: e_commerce_test
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    env:
      ECOMMERCE_DATABASE_TEST_URL: 'postgres://postgres:postgres@localhost:5432/e_commerce_test'
      ECOMMERCE_NODE_ENV: test
      SECRET: ${{secrets.SECRET}}
      SMTP_HOST_FROM: ${{secrets.SMTP_HOST_FROM}}
      SMTP_HOST_PASSWORD: ${{secrets.SMTP_HOST_PASSWORD}}
      FACEBOOK_APP_ID: ${{secrets.FACEBOOK_APP_ID}}
      FACEBOOK_APP_SECRET: ${{secrets.FACEBOOK_APP_SECRET}}
      FACEBOOK_CALLBACK_URL: ${{secrets.FACEBOOK_CALLBACK_URL}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      GOOGLE_CALLBACK_URL: ${{secrets.GOOGLE_CALLBACK_URL}}
      PASSWORD: ${{secrets.PASSWORD}}
      SALT: ${{secrets.SALT}}
      REDIS_URL: ${{secrets.REDIS_URL}}
      ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
      SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      CC_TEST_REPORTER_ID: 9da5e9efde1962e57dbb2a42fa661b1c77ae797093dd964d46e06d83a4447d3e